### PR TITLE
updated blob_eval: https://github.com/boris-kz/CogAlg/blob/master/intra_blob_draft.py

### PR DESCRIPTION
**Pull request by boris-kz**

### CODE REVIEW

**Comment by boris-kz** [comment]
You didn't post my updates?

**Comment by khanh93vn** [comment]
Sorry I didn't notice. I'll check and merge them with my current work.
About ablobs, I have a few questions:
 - Do we have to define new form_P(), scan_P_(), form_blob(), or use the
ones in frame_blobs()?
 - Each evaluated gblob will have a list of references to ablobs inside it.
Would there be asegments inside gsegment? aPs inside gP?


Vào Th 4, 16 thg 1, 2019 vào lúc 20:27 Boris Kazachenko <
notifications@github.com> đã viết:

**Comment by boris-kz** [comment]
Sure.

- Do we have to define new form_P(), scan_P_(), form_blob(), or use the
> ones in frame_blobs()?
>

Try to reuse them as much as possible.


> Would there be asegments inside gsegment? aPs inside gP.


I don't thinks so, but we may map them latter.

**Comment by khanh93vn** [comment]
Oh, do you mean this pull request? It has conflict that couldn't be resolved
And why did you want to replace the master branch with my fork? I deleted most of the files in my fork

**Comment by boris-kz** [comment]
Not sure what the conflict is, but you can copy blob_eval and edits in
comp_angle.
I didn't want to replace master branch, probably did something wrong.

**Pull request closed without merging**
